### ISSUE TITLE
dependency not found

### ISSUE THREAD

**Issue by SolarAquarion** [lirios/xdg-desktop-portal-liri#13]
/build/xdg-desktop-portal-liri-git/src/xdg-desktop-portal-liri/src/src.qbs:9:5 Dependency 'LiriNotifications' not found for product 'xdg-desktop-portal-liri'.

**Comment by plfiorini** [comment]
qbs is deprecated, see this issue for more info: https://github.com/lirios/lirios/issues/60
TL;DR: please use cmake, instead.
